[project]
name = "pygrader-web"
version = "1.0.0"
description = "Web version of the pygrader"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "pygrader",
    "streamlit>=1.51.0",
]

[dependency-groups]
dev = [
    "complexipy>=4.2.0",
    "coverage>=7.11.0",
    "flake8>=7.3.0",
    "mypy>=1.18.2",
    "pylint>=4.0.2",
]

[tool.uv.sources]
pygrader = { git = "https://github.com/fmipython/pygrader", rev = "v1.8.0" }

